spring.application.name=backend
# Veritaban? Adresi
spring.datasource.url=jdbc:postgresql://ep-still-pond-agkjbomt-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require

# Kullan?c? Ad? ve ?ifre
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IFkbBs7Temg1

# ?? GÜVENL? MOD: TABLOLAR ARTIK S?L?NMEYECEK (Temizlik bitti, update'e geri döndük)
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect