spring.application.name=backend

# 1. VER?TABANI AYARLARI (NEON)
spring.datasource.url=jdbc:postgresql://ep-still-pond-agkjbomt-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IFkbBs7Temg1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 2. PROFESYONEL GMAIL SMTP AYARLARI (ZAMAN A?IMI KORUMALI)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=unicycledestek@gmail.com
# Render'daki GMAIL_PASSWORD ortam de?i?kenini (16 haneli ?ifreyi) otomatik çeker
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
# Sonsuza kadar donmay? engelleyen güvenlik sigortalar? (5 saniye kural?):
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000