spring.application.name=backend

# Veritabani Adresi
spring.datasource.url=jdbc:postgresql://ep-still-pond-agkjbomt-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require

# Kullanici Adi ve Sifre
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IFkbBs7Temg1

# IS GUVENLI MOD: TABLOLAR ARTIK SILINMEYECEK (Temizlik bitti, update e geri donduk)
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect